name: EquipHideManager
version: 1.0-SNAPSHOT
main: com.gmail.bobason01.EquipHideManager
api-version: 1.13
author: crston
description: Player skins stand out when armor is not visible
commands:
  hidearmor:
    description: 수동으로 장비 숨기기 갱신
    usage: /<command>
    permission: equiphidemanager.hidearmor
permissions:
  equiphidemanager.hidearmor:
    description: 장비 숨기기 명령어 사용 권한
    default: true